# Generated by Django 5.1.4 on 2025-02-26 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GuessTheNumberInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('rounds', models.IntegerField(default=0)),
                ('accuracy', models.FloatField(default=0.0)),
                ('memory', models.TextField(default='')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
