# Generated by Django 5.1.4 on 2025-02-28 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guess_number', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuessNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('rounds', models.IntegerField(default=1)),
                ('accuracy', models.FloatField(default=0.0)),
                ('memory', models.TextField(default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='GuessTheNumberInfo',
        ),
    ]
