# Generated by Django 5.1.4 on 2025-05-11 05:33

import core.base_board
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='grid',
            field=models.TextField(default=core.base_board.base),
        ),
    ]
